### Create a new task
POST http://localhost:3001/tasks
Content-Type: application/json

{
  "title": "Leetcode",
  "description": "Code and Learn",
  "status": "to-do",
  "priority": "high",
  "duedate": "2025-08-10"
}

GET http://localhost:3001/tasks/?id=1